In [1]:
 import pandas as pd

In [3]:
df = pd.read_csv("8-apply_function_data.csv")

In [5]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [7]:
df.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [9]:
df.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [11]:
df.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [17]:
def salary_category(salary):
    if salary < 50000:
        return "low"
    elif 50000<= salary < 80000:
        return "medium"
    else:
        return "high"

In [19]:
df["Salary"].apply(salary_category)

0       high
1     medium
2        low
3     medium
4       high
       ...
95      high
96      high
97      high
98       low
99    medium
Name: Salary, Length: 100, dtype: object

In [21]:
df["Salary_Category"]= df["Salary"].apply(salary_category)

In [23]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,high
1,2,Emp_2,Sales,52662,24,3,medium
2,3,Emp_3,Finance,38392,5,3,low
3,4,Emp_4,Sales,60535,20,3,medium
4,5,Emp_5,Sales,108603,2,2,high
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high
96,97,Emp_97,Sales,100467,22,2,high
97,98,Emp_98,IT,82662,23,3,high
98,99,Emp_99,IT,42688,22,1,low
99,100,Emp_100,HR,55342,14,3,medium

In [38]:
def performance(experince):
    if experince > 10:
        return 1
    else:
        return 0

In [40]:
df["Experience"].apply(performance)

0     0
1     1
2     0
3     1
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: Experience, Length: 100, dtype: int64

In [51]:
df["Adjusted"]= df["Experience"].apply(performance) + df["Performance_Score"]

In [53]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted
0,1,Emp_1,Marketing,82251,6,5,high,5
1,2,Emp_2,Sales,52662,24,3,medium,4
2,3,Emp_3,Finance,38392,5,3,low,3
3,4,Emp_4,Sales,60535,20,3,medium,4
4,5,Emp_5,Sales,108603,2,2,high,2
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,5
96,97,Emp_97,Sales,100467,22,2,high,3
97,98,Emp_98,IT,82662,23,3,high,4
98,99,Emp_99,IT,42688,22,1,low,2
99,100,Emp_100,HR,55342,14,3,medium,4

In [55]:
df["Formatted_Name"] = df["Name"].apply(lambda x : x.replace("_"," "))

In [57]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,Formatted_Name
0,1,Emp_1,Marketing,82251,6,5,high,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,medium,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,low,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,medium,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,high,2,Emp 5
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,high,3,Emp 97
97,98,Emp_98,IT,82662,23,3,high,4,Emp 98
98,99,Emp_99,IT,42688,22,1,low,2,Emp 99
99,100,Emp_100,HR,55342,14,3,medium,4,Emp 100